package calc.vista;

import calc.servicios.CalcServices;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author Alex
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private CalcServices servicio;
    private boolean esResultado;
//    private CalController ctrl;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.servicio = new CalcServices();
        txtPantalla.requestFocus();
        esResultado = false;
        //btnBorrarCaracter.setBackground(new Color(212,59,27));
    }
    
    private void limpiarPantalla(){
       this.txtPantalla.setText("");
       this.txtTemp.setText("");
       txtPantalla.requestFocus();
    }
    
    private void pintarNumero(char n){
        if(esResultado){
            System.out.println("es resultado");
            this.btnBorrar.doClick();
            esResultado = false;
        }
        String text = this.txtPantalla.getText();
        if(!text.contains("-") || n!='-'){
            this.txtPantalla.setText(text + n);
            txtPantalla.requestFocus();            
        }
        
    }
    
    private void borrarCaracter(){
        String text = this.txtPantalla.getText();
        if(text.length()>0){
            
            if(text.equalsIgnoreCase("infinity")){
                this.limpiarPantalla();           
            }
            if(esResultado){
                this.limpiarPantalla();
                this.btnBorrar.doClick();
                esResultado = false;
            }else{
                this.txtPantalla.setText(text.substring(0, text.length()-1));
            }
            
        }
        txtPantalla.requestFocus();
    }
    
    private void ponerEnMemoria(String operador){
        try{
            String text = this.txtPantalla.getText();
            if((!text.equalsIgnoreCase("NaN")) && (!text.equalsIgnoreCase("infinity"))){
                
                if(text.length() > 0)
                    this.servicio.setTemp(Double.valueOf(text));
                else 
                    this.servicio.setTemp(0);
                
                this.servicio.setUltimoOperador(operador);
                this.limpiarPantalla();
                this.esResultado = false;
                this.txtTemp.setText((text.length()>0 ? text : '0') + " " + operador);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Error: numero no valido. " + e.getMessage());
        }
        txtPantalla.requestFocus();
        }
        
    private void obtenerResultado(){
        try{
            String text = this.txtPantalla.getText();
            String operador = this.servicio.getUltimoOperador();
            
            if(text.length()>0 && operador!=null){
                double resultado = this.servicio.calcular(Double.valueOf(text));
                this.txtPantalla.setText(String.valueOf(resultado));
                this.servicio.setUltimoOperador(null);
                esResultado = true;
                this.txtTemp.setText(this.txtTemp.getText() + " " + text + " =");
                this.servicio.setTemp(Double.NaN);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Error: numero no valido");
        }
        txtPantalla.requestFocus();
    }
    
    //Metodo para evitar la notacion cientifica
//    public static String convertir(double val){
//        Locale.setDefault(Locale.US);
//        DecimalFormat num = new DecimalFormat("#,###.00");
//        
//        return num.format(val);
//    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method ist always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSuma = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnBorrarCaracter = new javax.swing.JButton();
        btnModulo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtPantalla = new javax.swing.JTextField();
        txtTemp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSuma.setText("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 118, 55, -1));

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, -1, -1));

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 118, -1, -1));

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 118, -1, -1));

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 152, -1, -1));

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 152, -1, -1));

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 152, -1, -1));

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, -1, -1));

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 186, -1, -1));

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 186, -1, -1));

        btnResta.setText("-");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 152, 55, -1));

        btnMultiplicacion.setText("*");
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 186, 55, -1));

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 220, 55, -1));

        btnBorrar.setText("C");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 84, -1, -1));

        btnIgual.setBackground(new java.awt.Color(0, 0, 0));
        btnIgual.setForeground(new java.awt.Color(255, 255, 255));
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });
        jPanel1.add(btnIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 220, 92, -1));

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        btnBorrarCaracter.setBackground(new java.awt.Color(255, 51, 51));
        btnBorrarCaracter.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarCaracter.setText("←");
        btnBorrarCaracter.setBorderPainted(false);
        btnBorrarCaracter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarCaracterActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarCaracter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 84, -1));

        btnModulo.setText("MOD");
        btnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloActionPerformed(evt);
            }
        });
        jPanel1.add(btnModulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 84, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        txtPantalla.setEditable(false);
        txtPantalla.setBackground(new java.awt.Color(0, 0, 0));
        txtPantalla.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPantalla.setForeground(new java.awt.Color(51, 51, 255));
        txtPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPantalla.setBorder(null);
        txtPantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPantallaKeyPressed(evt);
            }
        });

        txtTemp.setEditable(false);
        txtTemp.setBackground(new java.awt.Color(0, 0, 0));
        txtTemp.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        txtTemp.setForeground(new java.awt.Color(204, 204, 204));
        txtTemp.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTemp.setBorder(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 60));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel1.setText("Acerca de");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloActionPerformed
        this.ponerEnMemoria("mod");
    }//GEN-LAST:event_btnModuloActionPerformed

    private void btnBorrarCaracterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCaracterActionPerformed
        this.borrarCaracter();
    }//GEN-LAST:event_btnBorrarCaracterActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        this.pintarNumero('0');
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        this.obtenerResultado();
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        this.limpiarPantalla();
        this.servicio.setTemp(Double.NaN);
        this.servicio.setUltimoOperador(null);
        this.esResultado = false;
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        this.ponerEnMemoria("/");
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        this.ponerEnMemoria("*");
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        if(this.servicio.getUltimoOperador() != null && !(this.txtPantalla.getText().length()>0 && !(this.txtPantalla.getText().equals("-"))) ){
            this.pintarNumero('-');
        }else{
            this.ponerEnMemoria("-");
        }
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        this.pintarNumero('3');
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        this.pintarNumero('2');
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        this.pintarNumero('1');
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        this.pintarNumero('6');
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        this.pintarNumero('5');
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        this.pintarNumero('4');
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        this.pintarNumero('9');
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        this.pintarNumero('8');
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        this.pintarNumero('7');
    }//GEN-LAST:event_btn7ActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        this.ponerEnMemoria("+");
    }//GEN-LAST:event_btnSumaActionPerformed

    private void txtPantallaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPantallaKeyPressed

        //Tecla borrar
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_BACK_SPACE:
                btnBorrarCaracter.doClick();
                //quitar sonido al borrar
                Action a;
                a = txtPantalla.getActionMap().get(DefaultEditorKit.deletePrevCharAction);
                a.setEnabled(false);
                break;
            case KeyEvent.VK_ADD:
                btnSuma.doClick();
                break;
            case KeyEvent.VK_SUBTRACT:
                btnResta.doClick();
                break;
            case KeyEvent.VK_MULTIPLY:
                btnMultiplicacion.doClick();
                break;
            case KeyEvent.VK_DIVIDE:
                btnDivision.doClick();
                break;
            case KeyEvent.VK_ENTER:
                btnIgual.doClick();
                break;
            
            case 46:
                this.pintarNumero('.');
                break;
            case 155:
            case KeyEvent.VK_0:
                btn0.doClick();
                break;
            
            case 35:   
            case KeyEvent.VK_1:
                btn1.doClick();
                break;
                
            case 40:
            case KeyEvent.VK_2:
                btn2.doClick();
                break;
                
            case 34:
            case KeyEvent.VK_3:
                btn3.doClick();
                break;
                
            case 37:
            case KeyEvent.VK_4:
                btn4.doClick();
                break;
                
            case 12:
            case KeyEvent.VK_5:
                btn5.doClick();
                break;
                
            case 39:
            case KeyEvent.VK_6:
                btn6.doClick();
                break;
            
            case 36:
            case KeyEvent.VK_7:
                btn7.doClick();
                break;
            
            case 38:
            case KeyEvent.VK_8:
                btn8.doClick();
                break;
            
            case 33:
            case KeyEvent.VK_9:
                btn9.doClick();
                break;
            default:
                servicio.imprimirMemoria();
//                char n = evt.getKeyChar();
//                this.pintarNumero(n);
                break;
        }

        System.out.println("Tecla: "+evt.getKeyCode());
    }//GEN-LAST:event_txtPantallaKeyPressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        JOptionPane.showMessageDialog(rootPane, "V3.16.05.2020\n-Ahora puedes usar el teclado\n-Changelog"
                + "\n-Correccion en la entrada de datos\n-Uso de excepciones\n-Efecto al presionar teclas\n"
                + "-Se puede mover libremente\n-Boton Salir eliminado\n-Boton borrar caracter detecta"
                + " cuando\nse debe borrar un resultado en vez de\neliminar cada caracter de este\n\n"
                + "V2.05.05.2020\n-Solucion error al presionar operador\ny resultado"
                + "\n-Implementacion opcion modulo");
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setForeground(new Color(57,100,236));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
                //JFrame.setDefaultLookAndFeelDecorated(true);
                VentanaPrincipal mainWindow = new VentanaPrincipal();
                mainWindow.setLocationRelativeTo(null);
                mainWindow.setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrarCaracter;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnModulo;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtPantalla;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
